pipeline:
  check:
    image: nixos/nix
    commands:
      - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - nix flake check
      - nix build
      - nix copy --to file:///var/lib/woodpecker-agent/nix-store $(realpath result)
    volumes:
      - /var/lib/woodpecker-agent/nix-store:/var/lib/woodpecker-agent/nix-store